// 📝 ÉPREUVE 7 — DEVINER UN MOT
// Format : { mot, interdits: [mots interdits], cat, alts: [orthographes acceptées en plus] }
// Les propositions sont comparées sans accents ni majuscules, avec une petite tolérance de frappe.

module.exports = [
  // ───── Audit & compta ─────
  { mot: 'Circularisation', interdits: ['client', 'banque', 'confirmation', 'audit', 'lettre'], cat: 'Audit' },
  { mot: 'Amortissement', interdits: ['immobilisation', 'durée', 'dotation', 'usure', 'linéaire'], cat: 'Compta' },
  { mot: 'Provision', interdits: ['risque', 'charge', 'litige', 'dépréciation', 'prudence'], cat: 'Compta', alts: ['provisions'] },
  { mot: 'Balance âgée', interdits: ['client', 'ancienneté', 'créance', 'retard', 'vieux'], cat: 'Audit', alts: ['balance agee'] },
  { mot: 'Lettrage', interdits: ['compte', 'rapprocher', 'facture', 'paiement', 'lettre'], cat: 'Compta' },
  { mot: 'Commissaire aux comptes', interdits: ['CAC', 'audit', 'certifier', 'mandat', 'six'], cat: 'Audit', alts: ['commissaire', 'cac'] },
  { mot: 'Bilan', interdits: ['actif', 'passif', 'comptes', 'clôture', 'annuel'], cat: 'Compta' },
  { mot: 'Inventaire', interdits: ['stock', 'compter', 'entrepôt', '31 décembre', 'palette'], cat: 'Audit' },
  { mot: 'Cut-off', interdits: ['exercice', 'rattachement', 'date', 'clôture', 'couper'], cat: 'Audit', alts: ['cutoff', 'cut off'] },
  { mot: 'Liasse fiscale', interdits: ['impôts', 'formulaire', 'déclaration', '2050', 'fisc'], cat: 'Compta', alts: ['liasse'] },
  { mot: 'Seuil de signification', interdits: ['matérialité', 'montant', 'erreur', 'audit', 'significatif'], cat: 'Audit', alts: ['seuil'] },
  { mot: 'Rapprochement bancaire', interdits: ['banque', 'relevé', 'écart', 'compte', 'rapprocher'], cat: 'Compta', alts: ['rapprochement'] },
  { mot: 'Feuille de temps', interdits: ['heures', 'timesheet', 'remplir', 'budget', 'vendredi'], cat: 'Cabinet', alts: ['feuilles de temps', 'timesheet'] },
  { mot: 'Facture', interdits: ['client', 'montant', 'TVA', 'payer', 'fournisseur'], cat: 'Compta' },
  { mot: 'TVA', interdits: ['taxe', 'valeur ajoutée', '20', 'impôt', 'collectée'], cat: 'Compta' },
  { mot: 'Goodwill', interdits: ['écart d’acquisition', 'rachat', 'survaleur', 'fusion', 'anglais'], cat: 'Compta' },
  { mot: 'Trésorerie', interdits: ['cash', 'banque', 'argent', 'liquidités', 'compte'], cat: 'Compta' },
  { mot: 'Stagiaire', interdits: ['jeune', 'apprendre', 'école', 'café', 'junior'], cat: 'Cabinet' },
  { mot: 'Lettre d’affirmation', interdits: ['signer', 'direction', 'déclaration', 'fin', 'représentation'], cat: 'Audit', alts: ['lettre d affirmation', 'lettre de representation'] },
  { mot: 'Point de revue', interdits: ['manager', 'commentaire', 'corriger', 'dossier', 'relire'], cat: 'Cabinet', alts: ['points de revue'] },
  { mot: 'Excel', interdits: ['tableau', 'Microsoft', 'cellule', 'formule', 'tableur'], cat: 'Cabinet' },
  { mot: 'RECHERCHEV', interdits: ['Excel', 'formule', 'chercher', 'colonne', 'vertical'], cat: 'Cabinet', alts: ['recherche v', 'vlookup'] },
  { mot: 'Busy season', interdits: ['période', 'clôture', 'janvier', 'travail', 'saison'], cat: 'Cabinet' },
  { mot: 'Fraude', interdits: ['voler', 'mentir', 'argent', 'détourner', 'escroquerie'], cat: 'Audit' },
  { mot: 'Échantillon', interdits: ['sondage', 'tirage', 'test', 'sélection', 'hasard'], cat: 'Audit', alts: ['echantillonnage'] },
  { mot: 'Dossier permanent', interdits: ['archive', 'statuts', 'document', 'mise à jour', 'toujours'], cat: 'Audit' },
  { mot: 'Note de frais', interdits: ['rembourser', 'restaurant', 'justificatif', 'dépense', 'ticket'], cat: 'Cabinet', alts: ['notes de frais'] },
  { mot: 'Chiffre d’affaires', interdits: ['ventes', 'CA', 'revenu', 'facturer', 'chiffre'], cat: 'Compta', alts: ['chiffre d affaires', 'ca'] },
  { mot: 'Compte d’attente', interdits: ['471', 'provisoire', 'suspens', 'classer', 'attendre'], cat: 'Compta', alts: ['compte d attente'] },
  { mot: 'Petite relance', interdits: ['mail', 'client', 'rappel', 'encore', 'relancer'], cat: 'Cabinet', alts: ['relance'] },
  { mot: 'Deadline', interdits: ['date limite', 'rendre', 'retard', 'urgent', 'échéance'], cat: 'Cabinet' },

  // ───── Bureau & entreprise ─────
  { mot: 'Machine à café', interdits: ['boire', 'expresso', 'pause', 'capsule', 'café'], cat: 'Bureau', alts: ['machine a cafe'] },
  { mot: 'Réunion', interdits: ['Teams', 'salle', 'discuter', 'point', 'ordre du jour'], cat: 'Bureau' },
  { mot: 'Télétravail', interdits: ['maison', 'distance', 'VPN', 'bureau', 'domicile'], cat: 'Bureau' },
  { mot: 'Open space', interdits: ['bureau', 'bruit', 'collègues', 'ouvert', 'espace'], cat: 'Bureau', alts: ['openspace'] },
  { mot: 'Séminaire', interdits: ['équipe', 'hôtel', 'formation', 'team building', 'week-end'], cat: 'Bureau' },
  { mot: 'Post-it', interdits: ['coller', 'jaune', 'papier', 'note', 'autocollant'], cat: 'Bureau', alts: ['postit', 'post it'] },
  { mot: 'Afterwork', interdits: ['bar', 'verre', 'soir', 'collègues', 'apéro'], cat: 'Bureau', alts: ['after work', 'after'] },
  { mot: 'Imprimante', interdits: ['papier', 'imprimer', 'bourrage', 'encre', 'scanner'], cat: 'Bureau' },
  { mot: 'Pot de départ', interdits: ['collègue', 'quitter', 'verre', 'cadeau', 'discours'], cat: 'Bureau' },
  { mot: 'Mot de passe', interdits: ['oublié', 'connexion', 'informatique', 'code', 'sécurité'], cat: 'Bureau', alts: ['mot de passe oublie', 'password'] },

  // ───── Football ─────
  { mot: 'Penalty', interdits: ['tir', 'gardien', 'onze mètres', 'faute', 'surface'], cat: 'Football', alts: ['penalti', 'pénalty'] },
  { mot: 'Hors-jeu', interdits: ['arbitre', 'position', 'défenseur', 'drapeau', 'ligne'], cat: 'Football', alts: ['hors jeu'] },
  { mot: 'Carton rouge', interdits: ['expulsion', 'arbitre', 'faute', 'sortir', 'couleur'], cat: 'Football' },
  { mot: 'Ligue des champions', interdits: ['Europe', 'coupe', 'C1', 'clubs', 'mardi'], cat: 'Football', alts: ['champions league'] },
  { mot: 'Ballon d’or', interdits: ['trophée', 'meilleur', 'joueur', 'France Football', 'Messi'], cat: 'Football', alts: ['ballon d or'] },
  { mot: 'Remontada', interdits: ['Barça', 'retour', 'PSG', 'renverser', '6-1'], cat: 'Football' },
  { mot: 'VAR', interdits: ['vidéo', 'arbitre', 'écran', 'assistance', 'revoir'], cat: 'Football' },
  { mot: 'Mercato', interdits: ['transfert', 'acheter', 'été', 'joueur', 'marché'], cat: 'Football' },
  { mot: 'Vestiaire', interdits: ['douche', 'mi-temps', 'entraîneur', 'se changer', 'casier'], cat: 'Football' },
  { mot: 'Coupe du monde', interdits: ['FIFA', 'quatre ans', 'pays', '1998', 'Mondial'], cat: 'Football', alts: ['mondial'] },
  { mot: 'Tirs au but', interdits: ['penalty', 'gardien', 'séance', 'égalité', 'prolongation'], cat: 'Football', alts: ['tir au but', 'tab'] },

  // ───── Vie quotidienne & culture ─────
  { mot: 'Croissant', interdits: ['viennoiserie', 'beurre', 'boulangerie', 'petit-déjeuner', 'pain au chocolat'], cat: 'Quotidien' },
  { mot: 'Raclette', interdits: ['fromage', 'fondre', 'hiver', 'pommes de terre', 'appareil'], cat: 'Quotidien' },
  { mot: 'Embouteillage', interdits: ['voiture', 'route', 'bouchon', 'trafic', 'périphérique'], cat: 'Quotidien', alts: ['bouchons'] },
  { mot: 'Lundi', interdits: ['semaine', 'jour', 'dimanche', 'début', 'matin'], cat: 'Quotidien' },
  { mot: 'Vacances', interdits: ['congés', 'plage', 'partir', 'repos', 'été'], cat: 'Quotidien' },
  { mot: 'Tour Eiffel', interdits: ['Paris', 'monument', 'fer', '1889', 'dame'], cat: 'Culture', alts: ['tour eiffel'] },
  { mot: 'Pyramide', interdits: ['Égypte', 'pharaon', 'triangle', 'Louvre', 'désert'], cat: 'Culture', alts: ['pyramides'] },
  { mot: 'Wi-Fi', interdits: ['internet', 'réseau', 'connexion', 'mot de passe', 'box'], cat: 'Quotidien', alts: ['wifi'] },
  { mot: 'Dinosaure', interdits: ['préhistoire', 'T-Rex', 'disparu', 'Jurassic', 'fossile'], cat: 'Culture' },
  { mot: 'Selfie', interdits: ['photo', 'téléphone', 'soi-même', 'réseaux', 'perche'], cat: 'Quotidien' },
  { mot: 'Astronaute', interdits: ['espace', 'fusée', 'Lune', 'Thomas Pesquet', 'combinaison'], cat: 'Culture', alts: ['cosmonaute', 'spationaute'] },
  { mot: 'Sudoku', interdits: ['grille', 'chiffres', 'neuf', 'japonais', 'case'], cat: 'Culture' },
];
